title: Giovanni Sinapi
url: "https://giovannisinapi.github.io"
baseurl: ""

markdown: kramdown
mathjax: true

tracking_id: #

plugins:
  - jekyll-seo-tag

sass:
    style: compressed
    sass_dir: _sass
